[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.png"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.mp4"
  [headers.values]
    Content-Type = "video/mp4"
    Accept-Ranges = "bytes"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.mp3"
  [headers.values]
    Content-Type = "audio/mpeg"
    Accept-Ranges = "bytes"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.mpeg"
  [headers.values]
    Content-Type = "audio/mpeg"
    Accept-Ranges = "bytes"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
